try {
    throw 'testing'
}catch(Error) {
    console.error(Error)
}